### ISSUE TITLE
Release zip names

### ISSUE THREAD

**Issue by aaron0browne** [chop-dbhi/data-models-validator#10]
I preferred the more specific zip names of the first release to the generic ones in the second. Small detail, I know. Pushing a change to the Makefile now. If others agree or disagree, make yourselves known.

**Comment by aaron0browne** [comment]
Fixed. Should I change the files on the release?

**Comment by bruth** [comment]
I can do a quick build.

**Comment by bruth** [comment]
Or rename..

**Comment by bruth** [comment]
Done.
