### ISSUE TITLE
Possibility of distributing a no-internet version?

### ISSUE THREAD

**Issue by aaron0browne** [chop-dbhi/data-models-validator#21]
Some folks are working behind a *very* restrictive firewall that denies outgoing internet requests. How much effort would be required to have an alternate version that caches the data model definitions at build time and then refers to them at runtime?

**Comment by bpetterson** [comment]
This is an issue with our organization as well. If at all possible I would like to do this as well. Currently working on trying to adjust to a local downloaded repository with little luck.

**Comment by bruth** [comment]
@bpetterson I responded to your email from yesterday with the following instructions:

Clone or download the data model files: https://github.com/chop-dbhi/data-models Cloning is recommended so you can periodically fetch the latest changes to keep in sync.

Download the data-models-service binary for your platform: https://github.com/chop-dbhi/data-models-service/releases/tag/1.0.1 and unzip it. Run the service pointing it to the data model files:

```
data-models-service -repo /path/to/data-model/files
```

Run `data-models-service -h` to list more options. By default it runs on http://localhost:8123 (you can open it up in a browser to view the data models).

Now that the service is running, it can be used by the data-models-validator. The binary can downloaded here: https://github.com/chop-dbhi/data-models-validator/releases/tag/1.0.2. Then run the validator an include the `-service` option to point to the locally running service.

```
data-models-validator -service http://localhost:8123 -model pedsnet -version 2.1.0 person.csv
```

**Comment by bruth** [comment]
Deeming this response as fixing the problem. For future reference there is now a [wiki page](https://github.com/chop-dbhi/data-models-validator/wiki#running-a-local-data-models-service).
