### ISSUE TITLE
Validator allows empty string values for timestamps, which fail to load

### ISSUE THREAD

**Issue by murphyke** [chop-dbhi/data-models-validator#27]
The `1.0.2-final` validator doesn't catch empty string values for timestamps (seen as `,"",` in the csv file), which then fail to load.

Obfuscated sample data showing problem in the 7th column:

```
"condition_occurrence_id","person_id","condition_concept_id","condition_start_date","condition_end_date","condition_start_time","condition_end_time","condition_type_concept_id","stop_reason","provider_id","visit_occurrence_id","condition_source_value","condition_source_concept_id"
"13123","76234","316993","2013-04-01",,"2013-04-01 7:00:00","","38000231","Active","3215","872634","397.0","44833554"
```

Load error in PostgreSQL:

```
ERROR:  invalid input syntax for type timestamp: ""
CONTEXT:  COPY condition_occurrence, line 2, column condition_end_time: ""
```

**Comment by bruth** [comment]
So is the timestamp column not nullable? According to the [docs](http://www.postgresql.org/docs/9.2/static/sql-copy.html), an empty string will be interpreted as a null value when reading a CSV formatted input. If it is, then it should interpret it as a null value, otherwise a value is required in which case it is a data issue.

**Comment by aaron0browne** [comment]
From that link to the docs:

> For example, with the default settings, a NULL is written as an unquoted empty string, while an empty string data value is written with double quotes (""). Reading values follows similar rules.

So the above value Kevin mentions is interpreted as an empty string, which is invalid input syntax for timestamp...

I think your confusion, Byron, is around whether the empty string is quoted or unquoted.

**Comment by bruth** [comment]
Ah, an *unquoted* empty string. I missed that part. The validator does not fix data it is validating, that is to say, it does not write new data out accounting for these discrepancies between our format and what Postgres expects. This logic could be built into the validator, but that would require sites to manage a new set of files being written to disk. I think it would be more appropriate to decouple this from the validator and add it as part of our data loading process.

**Comment by aaron0browne** [comment]
I think all this ticket is asking for is a validation check that does not allow for *quoted* empty string values in non-string-type columns.

**Comment by murphyke** [comment]
Exactly.

**Comment by bruth** [comment]
Understood. It was not clear from the description what the expected behavior should be.

**Comment by bruth** [comment]
I presume this expectation has been documented and communicated to sites? It is definitely a subtle thing and my concern is that most packages will either quote everything, not quote anything, or be lazy about it. I don't think most CSV writers consider the data type it is writing since it expects (or coerces) values to be string.

**Comment by murphyke** [comment]
Yes, this is probably the most odious requirement that the DCC has imposed on sites, and they are all painfully aware of it, with the exception of St Louis, who have a new person working on their ETL.  I think we just adopted a standard PostgreSQL approach and hoped it would work for everyone.  In the future, we should consider a spec that is easy for all the sites to conform to using standard tools.  The current requirement is that NULLs be represented by unquoted empty values.  So if you don't have an export tool that allows selection of an arbitrary NULL placeholder (and that doesn't wrap it in quotes if quoting is on), then you have to roll custom export code, which is no good.

**Comment by bruth** [comment]
Does #24 make this issue moot?

**Comment by murphyke** [comment]
Yes, it should, we load (COPY) all columns with the FORCE_NULL option to the CSV format.  I'll close this to promote sanity.
