### ISSUE TITLE
error decoding model

### ISSUE THREAD

**Issue by daneckrich** [chop-dbhi/data-models-validator#28]
when I run the validator I only get the error:

error decoding model revisions: invalid character '<' looking for beginning of value

using -model pedsnet -version 2.1.0

it happens from the first attempt, so it doesn't seem to be the same issue as the Client error on fast repeat runs

**Comment by aaron0browne** [comment]
@daneckrich Please try running the validator with the following added flag: `-service https://data-models-service.research.chop.edu/` and report back.

@bruth It looks like the validator is not properly following the new URL redirect...

**Comment by daneckrich** [comment]
adding -service https://data-models-service.research.chop.edu/ seems to work

thank you

**Comment by aaron0browne** [comment]
@daneckrich We've just released a new version of the software, which you can download [here](https://github.com/chop-dbhi/data-models-validator/releases/tag/1.0.3), that you won't need to use the `-service` flag with.

**Comment by bruth** [comment]
This was due to redirects not being handled correctly. The [1.0.4 release](https://github.com/chop-dbhi/data-models-validator/releases/tag/1.0.4) handles this correctly.
